# SPDX-FileCopyrightText: Copyright (c) 2026 Illia Brashkin
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    "**.json",
    "**.md",
    "**.txt",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2026 Illia Brashkin"
SPDX-License-Identifier = "MIT"
