# SPDX-FileCopyrightText: Copyright (c) 2026 Illia Brashkin
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: actionlint
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  actionlint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
