# SPDX-FileCopyrightText: Copyright (c) 2026 Illia Brashkin
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: npm
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  npm:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm exec -- lefthook run pre-push --no-tty --no-auto-install
