# SPDX-FileCopyrightText: Copyright (c) 2026 Illia Brashkin
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: npm
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  npm:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run lint:pkg
      - run: npm run format:pkg:check
      - run: npx tsc --noEmit
